### Import Numpy and use alice name as 'np'.

In [3]:
import numpy as np

## Write a NumPy program to test whether none of the elements of a given array is zero.

In [7]:
np_arr = np.array([5,4,6,7]) # creating NP array with a list of integers
# all() method returns True if none of its elements is 0 else returns False
print("Does this Numpy array having none of its elements as zero? ",np_arr.all(),np_arr)
np_arr[0] = 0
print("Does this Numpy array having one of its elements as zero? ",np_arr.all(),np_arr)

Does this Numpy array having none of its elements as zero?  True [5 4 6 7]
Does this Numpy array having one of its elements as zero?  False [0 4 6 7]


## Write a NumPy program to create an array of 5 zeros, 5 ones, 5 fives.

In [10]:
zeros = np.zeros(5)
ones = np.ones(5)
fives = np.ones(5)*5
np.concatenate((zeros,ones,fives), axis=0)

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 5., 5., 5., 5., 5.])

## Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [11]:
norm_dist = np.random.normal(0,1,15)
print("15 random numbers from a standard normal distribution:")
print(norm_dist)

15 random numbers from a standard normal distribution:
[-0.67934724 -0.11889141  1.11941274  0.28954816  0.15586675 -0.20170945
 -0.11506066 -0.48427136 -1.30198035 -1.65242604  0.68131856 -1.79237667
 -0.38516601  0.54170829 -0.03730219]


## For  following Array
- A=[[1,2,3],[5,6,7],[13,14,-8]
- B =[[[1,1,1],[2,3,4]],[[2,5,7],[3,8,7]]]
Find:
    - 1. Mean of second row(A) and mean of first row from first axis(B)
    - 2. Reshape array B and save it to a variable C
    - 3. Do matrix multiplication of array C and a unity matrix(create shape according to the mul properties)
    - 4. create a subset for  row 3 of matrix A and save it in variable d. 

In [20]:
A = [[1,2,3],[5,6,7],[13,14,-8]]
B = [[[1,1,1],[2,3,4]],[[2,5,7],[3,8,7]]]

print(f"Mean of Second row {A[1]} of A = ",np.mean(A[1]))

C = np.array(B).reshape(4,3)

print(C)



Mean of Second row [5, 6, 7] of A =  6.0


array([[1, 1, 1],
       [2, 3, 4],
       [2, 5, 7],
       [3, 8, 7]])

## Write a NumPy program to create a vector with values ranging from 10 to 40 and print all values except the first and last.

In [22]:
vectors = np.arange(10,40)
print("Original vector:")
print(vectors)
print(" \nExcluding first and last element: ")
print(vectors[1:-1])

Original vector:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39]
 
Excluding first and last element
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38]


## Write a NumPy program to create a vector with values from 1 to 15 and change the sign of the numbers in the range from 10 to 15. 

In [23]:
vectors = np.arange(15)
print("Original vector:")
print(vectors)
print("After changing the sign of the numbers in the range from 9 to 15:")
vectors[(vectors >= 10) & (vectors <= 15)] *= -1
print(vectors)

Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
After changing the sign of the numbers in the range from 9 to 15:
[  0   1   2   3   4   5   6   7   8   9 -10 -11 -12 -13 -14]


## Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

In [27]:
np_arr = np.arange(10,22).reshape(3,4)
np_arr

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

## Write a NumPy program to compute the inner product of two given vectors

In [28]:
vectors1 = np.array([4, 5])
vectors2 = np.array([7, 10])
print("Original vectors:")
print(vectors1)
print(vectors2)
print("Inner product of said vectors:")
print(np.dot(vectors1, vectors2))

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78


## Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.

In [29]:
import numpy as np
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
# create a structured array
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("Sort by height")
print(np.sort(students, order='height'))    

Original array:
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
Sort by height
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


## Write a NumPy program to add, subtract, multiply, divide arguments element-wise. 

In [31]:
print("Add:", np.add(1.0, 4.0))
print("Subtract:", np.subtract(1.0, 4.0))
print("Multiply:", np.multiply(1.0, 4.0))
print("Divide:", np.divide(1.0, 4.0))

Add: 5.0
Subtract: -3.0
Multiply: 4.0
Divide: 0.25


 ## Write a NumPy program to get the minimum and maximum value of a given array along the second axis.

In [33]:
np_arr = np.arange(15).reshape((5, 3))
print("\nOriginal array:")
print(np_arr)
print("\nMaximum value along the second axis:")
print(np.amax(np_arr, 1))
print("Minimum value along the second axis:")
print(np.amin(np_arr, 1))


Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

Maximum value along the second axis:
[ 2  5  8 11 14]
Minimum value along the second axis:
[ 0  3  6  9 12]


## Write a NumPy program to display all the dates for the month of May, 2019

In [34]:
print("May, 2019")
print(np.arange('2019-05', '2019-06', dtype='datetime64[D]'))

May, 2019
['2019-05-01' '2019-05-02' '2019-05-03' '2019-05-04' '2019-05-05'
 '2019-05-06' '2019-05-07' '2019-05-08' '2019-05-09' '2019-05-10'
 '2019-05-11' '2019-05-12' '2019-05-13' '2019-05-14' '2019-05-15'
 '2019-05-16' '2019-05-17' '2019-05-18' '2019-05-19' '2019-05-20'
 '2019-05-21' '2019-05-22' '2019-05-23' '2019-05-24' '2019-05-25'
 '2019-05-26' '2019-05-27' '2019-05-28' '2019-05-29' '2019-05-30'
 '2019-05-31']


## Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array

In [35]:
import numpy as np
x = np.array(['ml', 'PYTHON', 'Data Science', 'Numpy'], dtype=np.str)
print("Original Array:")
print(x)
capitalized_case = np.char.capitalize(x)
lowered_case = np.char.lower(x)
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case)

Original Array:
['ml' 'PYTHON' 'Data Science' 'Numpy']

Capitalized:  ['Ml' 'Python' 'Data science' 'Numpy']
Lowered:  ['ml' 'python' 'data science' 'numpy']
Uppered:  ['ML' 'PYTHON' 'DATA SCIENCE' 'NUMPY']
Swapcased:  ['ML' 'python' 'dATA sCIENCE' 'nUMPY']
Titlecased:  ['Ml' 'Python' 'Data Science' 'Numpy']
